In [38]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [84]:
# Load sales data and print first 5 items
# SALES = pd.read_csv("../data/items_purchased.csv")
SALES = pd.read_csv("~/Desktop/items_purchased.csv")
SALES.head()

,kiosk_id,product_id,card_hash,date_time,fc_number
0,108,2457,FEaD8IUmESlpzvPRYyZhMyUv/CRtDNIUyprR5w7e/mPkFz...,2017-12-06 22:06:36-08,20.0
1,220,2884,N8JjRgpqKnQ8BDp+XtxBkfM0If/9GBL+rsOalHjHLdIM8B...,2018-08-08 14:18:09-07,NaN
2,182,2937,svL2pR3SC6O+B/Kg+78gJsiKDxvCtSUohDLGjj02tGC0MS...,2017-10-20 18:22:10-07,NaN
3,339,3814,kzaHILrWFehUeo6gjZV1EwvZHNTXGNqTY/Hzv+mL9Bg+vR...,2018-06-13 01:30:06-07,48.0
4,230,4149,4ox+j2exAB/xLlyHteKO/cNoSdLFb3T29mkacbTAf7ECiX...,2017-10-19 16:27:17-07,NaN

In [46]:
# List 300 most popular products
# Very curious to know what product_id 4061 is. Chips? 
report = SALES.groupby('product_id').product_id.count().reset_index(name ='count')
report = report.sort_values(by='count', ascending=False)

print("300 Most Popular Products")
report.head(n=300)

#report.plot.bar();

300 Most Popular Products

     product_id  count
70         4061  68369
102        4202  32361
240        4793  27828
4          2360  26496
104        4207  24443
103        4203  22463
137        4319  21524
37         2941  20630
51         3815  19084
9          2603  17392
52         3816  16201
113        4243  15888
141        4349  15634
151        4403  14667
152        4404  14297
123        4258  14030
66         3991  13988
10         2604  13862
208        4630  13670
0          2350  13296
172        4497  12190
46         3445  12101
116        4246  11581
194        4543  11031
76         4101  10810
292        5386  10057
136        4318  10041
44         3422   9723
226        4709   9651
115        4245   9546
..          ...    ...
328        6122     37
315        5701     35
89         4166     35
184        4513     34
317        5705     33
133        4300     33
174        4499     30
130        4297     28
259        4873     27
69         4058     26
58         3933     25
199        4562     24
180        4506     22
179        4505     18
65         3981     15
200        4563     13
204        4614     13
163        4449     12
35         2890     12
198        4561     11
88         4163      9
90         4167      7
64         3980      7
53         3818      6
87         4162      6
36         2937      5
160        4430      4
42         3172      4
24         2864      4
61         3965      4

[300 rows x 2 columns]

In [81]:
# Most popular products at each kiosk
report = SALES.groupby(['kiosk_id', 'product_id']).size().reset_index(name='count')
report = report.sort_values(by='count', ascending=False)

print("Most Popular Products By Kiosk")
report.head(n=100)

Most Popular Products By Kiosk

       kiosk_id  product_id  count
39259       750        4061    862
10275       423        4061    755
19384       530        4061    599
18785       527        4061    590
259          58        4061    563
46092       830        4061    563
10485       424        4061    560
10868       427        4061    554
33015       654        4061    535
26597       589        4061    534
58028       956        4061    519
5428        303        4061    505
34918       680        4061    490
24675       571        4061    483
6705        356        4061    465
8945        407        4061    462
8071        396        4061    454
65630      1052        4061    454
1027        108        4061    454
32973       654        2350    449
17953       523        4202    439
17737       522        4061    436
43806       801        4061    423
18992       528        4061    418
42           29        4061    412
46312       831        4061    407
17937       523        4061    406
30503       636        4061    406
10234       423        2350    405
18991       528        3991    403
...         ...         ...    ...
36744       697        4061    319
26559       589        2360    318
10446       424        2350    317
16487       501        4061    317
26206       586        4061    316
44831       810        4061    316
43630       800        4061    315
25625       581        2350    313
9162        408        4061    313
39466       751        4061    312
39281       750        4243    311
42719       788        4061    310
35023       680        4793    308
18165       524        4203    308
15533       495        4061    308
17955       523        4207    306
4830        255        4202    303
10237       423        2360    302
38422       730        4061    302
23925       564        4061    301
66025      1055        4061    301
19980       533        4061    300
62587      1008        4061    300
42334       785        4061    300
49684       862        4061    299
3355        196        4061    299
46562       834        4061    298
16453       501        2360    297
18821       527        4319    293
30602       636        4793    293

[100 rows x 3 columns]

In [72]:
# Most popular product categories
report = SALES.groupby('fc_number').product_id.count().reset_index(name ='count')
report = report.sort_values(by='count', ascending=False)

print("Most Popular Product Categories")
report.head(n=46)

Most Product Categories

    fc_number  count
29       35.0  86592
20       25.0  68369
12       14.0  63856
10       12.0  58080
18       23.0  53820
21       26.0  53348
14       16.0  50860
5         7.0  45717
45       53.0  44653
36       43.0  44084
32       38.0  43233
35       42.0  39478
1         2.0  35285
41       49.0  32783
44       52.0  28964
17       20.0  25480
2         3.0  25041
7         9.0  24313
33       40.0  23094
40       48.0  22466
26       31.0  20782
15       18.0  20246
4         6.0  18577
11       13.0  18025
23       28.0  17125
42       50.0  16521
16       19.0  15387
38       45.0  15246
9        11.0  13672
8        10.0  13649
34       41.0  12190
28       34.0  12182
30       36.0   8861
3         5.0   8516
37       44.0   8273
31       37.0   6666
39       47.0   6299
24       29.0   4813
0         1.0   2548
13       15.0   2235
6         8.0   1781
43       51.0   1497
25       30.0    239
19       24.0     93
22       27.0     40
27       33.0      1

In [75]:
# Most lucrative kiosks
report = SALES.groupby('kiosk_id').product_id.count().reset_index(name ='count')
report = report.sort_values(by='count', ascending=False)

print("50 Most Lucrative Kiosks")
report.head(n=50)

50 Most Lucrative Kiosks

     kiosk_id  count
261       750  12295
177       589  11533
230       680  11119
33        303  10190
311       831   9468
402       956   9307
70        423   9120
310       830   9060
1          58   8941
401       955   8265
132       528   7818
40        356   7698
172       581   7642
5         108   7534
37        340   7482
71        424   7286
434      1008   7131
203       636   7088
16        182   7034
0          29   6978
338       862   6851
455      1052   6834
131       527   6763
217       654   6662
140       536   6620
3          71   6372
142       539   6350
202       635   6277
32        280   6260
341       866   6237
127       523   6229
289       790   5949
134       530   5882
139       535   5856
126       522   5834
144       541   5763
130       526   5708
143       540   5690
280       775   5679
133       529   5674
212       649   5590
182       598   5558
137       533   5533
242       697   5525
128       524   5503
141       538   5500
194       620   5447
249       705   5351
164       571   5310
116       500   5293

In [78]:
# Repeat Customers
# Whoever pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidlZpC1Md3ilg1NvM19ip8WAvilcMdy8siy5whPtAKA== must be a corporate account
report = SALES.groupby('card_hash').product_id.count().reset_index(name ='count')
report = report.sort_values(by='count', ascending=False)

print("Repeat Customers")
report.head(n=50)

Repeat Customers

                                                card_hash  count
100947  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...  24467
105875  sZcYIySlDHP+sxK0GF8ZUSMYqFnoLQrbtLmsPGt+NT+ukG...   1688
116280  y4u3ViaqERLVpLdauGsClhX1v4DdxsZ2yr86TYYd7FVTzn...   1444
61625   V+trkgPKWB3Ah4u2Wq05EEPaicgnC7f6Mp+Kazbl1QZS2Z...    791
55160   RT09yBDAn5SvTjwiN5Qv5MQYPI2dUGrN6pVeHimAfvLuRE...    787
10679   3jThs4CWlxmW2ttPDkxsOlaHvMr2DZE8d44SOs13JdYKcC...    745
73654   bNakfBB3xWoCn8MZy03wMW069LsLsYF9wdKc+6uB30CmKn...    698
95371   mvqlnyiysM3Gim5u1S7fbs8TwR9Ivv9WsxJcg6nHDmSKip...    686
96122   nJqefwWsi08TlTzFhaHI84Gl6N7B0l7AR+u3lTgrjGa7gh...    680
45541   MKK69j+bCHjQBuFvoWBdh3KdpzMvs2Q//4ckTaw0uyGI22...    648
15079   64LcsIctWnPrGaXfcW+gPRBJq5akh84HNEuUWbemoFZT8Y...    610
26605   CEBWk62ko6AeTxvr2s7mbCjAWQpHzNskY7HRHhyD624oQp...    603
68898   Yr9t0hCYmzxAhgjrZIUxaxrnXH81tRP3oaSARGqix43w03...    592
24857   BKPWHPaHqyHhijnurEEhvBR5Gbbv0ZSQIpplPLNGwzX2OQ...    562
91186   kiAaa0LTIHmGQAr9S8FjevqhULu7lAb8C6HlhxzCTJP1J0...    554
106974  tB25ivfXgo9ivEWb3mcFT6wme+VsNoQANobTOcKhQjSFZq...    540
28245   D95SohoilSTX2arrm+/S+qohXejgZO69ozF0wmm8E5vsW9...    531
38434   IaR+uu2ayWFz0I8mBnCOHotq9R4p9hY4rDaCcmFt4Siuds...    529
103100  r5VMQssLySo5tsl/cs9izhXQCdA9+TqKFsf8WmEuXpg8IB...    526
32253   FEaD8IUmESlpzvPRYyZhMyUv/CRtDNIUyprR5w7e/mPkFz...    522
59362   TlbVhCRSTkSNt9CHpbjMeNcRHmvYMSWlusbT3BB/sgbJhj...    504
79816   ecort9rzM3gHIUNDKoWMHsEn3AkcctjEnzEVJE9qhujTNK...    498
103267  rAoIqonLKDM1JVWK9J2d0y9rapVPmJ9BObQdQJ7/1T+snj...    491
107492  tS7LD1lU6lsEZfqkK63TzgmmTxH6IVefV7eqws9YSeWOfM...    487
100985  pyhSrg374uxy/wjyqruij4g5ZuZ6rewo3PgqjQ6YOYEX1v...    478
37183   HvaDq1C2FqjE5nbX9ZrwmhR1aviWHH82iC5LALWSwaf1qW...    473
45747   MQuxxJLdKlgbppXT/cOuvwgaOCpuT+TIIQAWHnKkovyXjB...    471
76523   cxW/fGnQnr6wuKhXrZVNQ3ej+jtEUYRk6l8hhtCafpefUB...    471
2605    /PAdqVPSG469RgBZw9wYko38C3/jmuGKBzaUuJlJcQhXgs...    467
86453   iAFL7aSV3wLn6XbyikOOE2lsAIs+5qlMIaKy+smFGm7alY...    459
116227  y2fCV+9ckV7ZpdMZxunaEKpsNFIEZjfWwI3pdNMApDsTq6...    448
98112   oPVmSgv4KqYpZN662XqlVUUnf5gCGg4jtNge8FdJ6Vl0Ks...    446
82551   g4MGaipqEHCLyG9qRqnFdG4VjJOCQBrOHqWrB4dJEZjfKl...    445
68548   YgRQ5lZGOz5zOsXu1LQX4SiIDhM4LQ47mrNz2fAWoLRNxZ...    441
55808   RpUgvBfafXkjX2edCBR8ZdsBQGIA24/YWFpTKtQdCvySFQ...    440
3522    /unBoFPtYmxgJ6NL2CAuir5t1BycRxWEPJFDIYG/GMs+/U...    436
42153   KWDKgnFICmNeYYwUKf4gxmsGZx4Ye+pr3IvWsBqr76bpqm...    432
35321   GxY0esapnt6AawFARK0jKDnu4q94mQ9facSK4e3lBSrxiB...    430
6025    1EKafIiRoAw2yNGfLi937Oz/i/YLQbGG3ea3783xYvxYcm...    429
59412   TnbYG6JW/Hb0STJ/Xz6pPZSWNCxDbLAJC/W7du0Wq+AvHg...    429
106768  t3Okzg1ZDyym0F7Eey0tZwGjnj0CnKH5zxL9Xa5i+6ktRf...    427
62652   VXfjiGwpr7kUTCWpeb2W03+3p4sniQAplAm6JG1XYfcO0p...    415
87183   iaBPRHYty82L0GEO5dBmyelCc+BZVsbuyksSvstHi+iHVo...    411
59420   TnzIK5ZVFeRckUdR+0bwwBttX0NBvDFAnE1gwARocjlXXD...    409
37249   Hy6yWBpLVGW70remRpJcReI7080sgiqH0vv8TIOvizZnHQ...    408
42421   KgCAJojH8u8lgkqK+eZpRKJZAbrDozIq9k0GxmgcsRk9A7...    407
13789   5Oqf3WjL8r4haFx5PY7/RVS1JFN/zRok6WPQ9+qST8uaU4...    404
22978   AIfB4FaFCAuLIkzSGL2NmTq56n4svr8Zw1ErIfD0IJ8ZL3...    401
20650   91JFUYAc4FtEhDvrUnm8iW0W5exTGsAF706C73gpulg/W4...    400
106339  sqnyfQiup2tbTBQe6vbbBS22U627GLp5VtxrF98aW/Ljm6...    393

In [80]:
# Do repeat customers purchase the same items over and over?
report = SALES.groupby(['card_hash', 'product_id']).size().reset_index(name='count')
report = report.sort_values(by='count', ascending=False)

print("Repeat Customer Purchases")
report.head(n=100)

Most Popular Products By Kiosk

                                                card_hash  product_id  count
473758  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4061   1677
473881  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4793    807
473737  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2941    635
473773  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4202    551
473708  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2350    543
447585  mvqlnyiysM3Gim5u1S7fbs8TwR9Ivv9WsxJcg6nHDmSKip...        5465    531
473711  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2360    525
473775  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4207    500
473803  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4319    475
473807  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4349    451
473714  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2603    422
473774  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4203    394
473793  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4258    382
473715  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2604    361
473849  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4543    320
473747  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        3815    316
473858  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4630    314
473903  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4947    298
290930  V+trkgPKWB3Ah4u2Wq05EEPaicgnC7f6Mp+Kazbl1QZS2Z...        4061    294
473748  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        3816    279
473802  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4318    275
473827  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4453    266
473833  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4497    264
215451  MKK69j+bCHjQBuFvoWBdh3KdpzMvs2Q//4ckTaw0uyGI22...        4403    257
473904  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4948    256
473786  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4246    243
473810  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4353    238
473868  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4709    232
473743  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        3422    217
473744  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        3445    205
...                                                   ...         ...    ...
84058   7VdybYQfLqJaxRazVJVOo2LtxvO/8M1wWIi40gBBQ0xGiB...        4061    128
473725  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2860    128
473892  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4858    127
473819  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4407    127
259628  RPq5uQEpuFW9KFu3JKTTf0mXMDutpOBHig6UtfXBt7qTjQ...        2360    123
389651  g9W3Ic/7ipo+2uzk7sjlPGEWCps8CVBFz1+o7fSbjwO+tS...        4061    122
473910  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        5112    122
473832  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4496    121
473870  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4711    121
473782  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4219    121
228516  No0gVdAKd69KfomdgpuH6lOe8UWJBbxRBC44SjJOo2fvly...        2360    121
530718  wERIRLyZplW3zJnS/1MzOTzhpGCcWZHH/297bCr89thgPN...        4061    121
473925  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        5328    120
473756  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        3991    120
473848  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4542    117
473835  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4501    117
473909  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        5111    116
473871  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4712    115
473908  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        5110    114
382293  fHRAGY3lSwtAIKWOF056GRDUJpLs0Ln0oerIeM7yfOxDZN...        2603    114
275343  TD4cDQhMydGTWhPVAHrbExe7hzEmnN7UMRdHAdCFYTCzcK...        3815    112
473934  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        5423    111
473753  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        3950    111
473722  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2856    110
492666  s/oenvoH8sNM4HFTTf5tmNJpnNmAD34WmupxKtfz/1usEp...        4061    109
473721  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2854    106
473887  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        4802    105
473710  pxWdKu6voFceSKpehBo0XZ6EJF5N0UDXWvnd/EbM46cidl...        2358    105
506482  tXJ2hsYRz75mTobByvPFEkym0qrbeNAbOMBYuu3jOf+oAS...        4403    104
112675  AdL794VPhUn1yXUICwn1/LinbsOgUTkyjZBqSYcu7usyVv...        3991    103

[100 rows x 3 columns]